app <- ShinyDriver$new("../../", loadTimeout = 100000, seed = 1234)
app$snapshotInit("simple_assay_change")

Sys.sleep(0.5)
app$setInputs(Marker_1 = "CD99")
app$setInputs(tabbox1 = "tab2")
app$snapshot()
app$setInputs(assay = "exprs")
app$snapshot()
app$setInputs(tabbox1 = "tab2")
app$snapshot()
app$setInputs(assay = "counts")
app$snapshot()
app$setInputs(tabbox1 = "tab2")
app$snapshot()
app$setInputs(Marker_1 = "CDH")
app$setInputs(tabbox1 = "tab2")
app$setInputs(resetMarkers = "click")
app$snapshot()
app$setInputs(assay = "exprs")
app$snapshot()
app$setInputs(tabbox1 = "tab2")
app$snapshot()
app$setInputs(assay = "counts")
app$snapshot()
app$setInputs(tabbox1 = "tab2")
app$snapshot()

p <- app$.__enclos_env__$private$shinyProcess
p$interrupt()
p$wait()
