app <- ShinyDriver$new("../../", loadTimeout = 100000, seed = 1234)
app$snapshotInit("tab_select")

Sys.sleep(0.5)
app$snapshot()
app$setInputs(tabbox1 = "tab2")
#app$snapshot()
app$setInputs(tabbox1 = "tab1")
app$setInputs(Marker_1 = "CD99")
app$snapshot()
app$setInputs(tabbox1 = "tab2")
#app$snapshot()
app$setInputs(resetMarkers = "click")
#app$snapshot()
app$setInputs(tabbox1 = "tab1")
app$setInputs(Marker_1 = "CD8a")
app$snapshot()
app$setInputs(tabbox1 = "tab2")
#app$snapshot()
app$setInputs(resetMarkers = "click")
#app$snapshot()

p <- app$.__enclos_env__$private$shinyProcess
p$interrupt()
p$wait()