test_that("User interface is correctly rendered", {
    cur_header <- .cytomapper_header()
    
    expect_equal(cur_header$name, "header")
    expect_equal(cur_header$attribs$class, "main-header")
    expect_null(cur_header$children[[1]])
    expect_equal(as.character(cur_header$children[[2]]), paste0('<span class="logo">cytomapper v',
                        packageVersion("cytomapper"), '</span>'))
    expect_equal(as.character(cur_header$children[[3]]), "<nav class=\"navbar navbar-static-top\" role=\"navigation\">\n  <span style=\"display:none;\">\n    <i class=\"fa fa-bars\"></i>\n  </span>\n  <a href=\"#\" class=\"sidebar-toggle\" data-toggle=\"offcanvas\" role=\"button\">\n    <span class=\"sr-only\">Toggle navigation</span>\n  </a>\n  <div class=\"navbar-custom-menu\">\n    <ul class=\"nav navbar-nav\">\n      <li class=\"dropdown notifications-menu\">\n        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n          <i class=\"fa fa-fas fa-download\"></i>\n        </a>\n        <ul class=\"dropdown-menu\">\n          <li class=\"header\"></li>\n          <li>\n            <ul class=\"menu\">\n              <li>\n                <a href=\"#\">\n                  <i class=\"fa fa- text-info\"></i>\n                  <div class=\"form-group shiny-input-container\">\n                    <label class=\"control-label\" for=\"labelCellsBy\">Cell label</label>\n                    <input id=\"labelCellsBy\" type=\"text\" class=\"form-control\" value=\"Cell-Type\"/>\n                  </div>\n                </a>\n              </li>\n              <li>\n                <a href=\"#\">\n                  <i class=\"fa fa- text-info\"></i>\n                  <a id=\"downloadData\" class=\"btn btn-default shiny-download-link \" href=\"\" target=\"_blank\" download style=\"background-color: #3C8DBC; color: white; border-color: #7EA6F8\">\n                    <i class=\"fa fa-download\"></i>\n                    Download selection\n                  </a>\n                </a>\n              </li>\n            </ul>\n          </li>\n        </ul>\n      </li>\n      <li class=\"dropdown tasks-menu\">\n        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n          <i class=\"fa fa-fas fa-question\"></i>\n        </a>\n        <ul class=\"dropdown-menu\">\n          <li class=\"header\"></li>\n          <li>\n            <ul class=\"menu\">\n              <li>\n                <a href=\"#\">\n                  <i class=\"fa fa- text-info\"></i>\n                  <button id=\"SessionInfo\" type=\"button\" class=\"btn btn-default action-button\" style=\"background-color: #3C8DBC; color: white; border-color: #3C8DBC\">Session Info</button>\n                </a>\n              </li>\n              <li>\n                <a href=\"#\">\n                  <i class=\"fa fa- text-info\"></i>\n                  <button id=\"Help\" type=\"button\" class=\"btn btn-default action-button\" style=\"background-color: #3C8DBC; color: white; border-color: #3C8DBC\">Help</button>\n                </a>\n              </li>\n            </ul>\n          </li>\n        </ul>\n      </li>\n    </ul>\n  </div>\n</nav>")

    
})

