app <- ShinyDriver$new("../../", loadTimeout = 100000, seed = 1234)
app$snapshotInit("image_tab_selection")

app$setInputs(assay = "counts")
app$setInputs(Marker_1 = "PIN")
app$snapshot()
app$setInputs(tabbox1 = "tab2")
app$snapshot()
app$setInputs(tabbox1 = "tab1")
app$snapshot()
app$setInputs(Marker_2 = "CD8a")
app$snapshot()
app$setInputs(tabbox1 = "tab2")
app$snapshot()
app$setInputs(tabbox1 = "tab1")
app$snapshot()

p <- app$.__enclos_env__$private$shinyProcess
p$interrupt()
p$wait()