app <- ShinyDriver$new("../../", loadTimeout = 100000, seed = 1234)
app$snapshotInit("next_prev_sample_change")

Sys.sleep(0.5)
app$setInputs(Marker_1 = "CD99")
app$snapshot()
app$setInputs(`next.sample` = "click")
app$snapshot()
app$setInputs(`next.sample` = "click")
app$snapshot()
app$setInputs(`next.sample` = "click")
app$snapshot()
app$setInputs(`previous.sample` = "click")
app$snapshot()
app$setInputs(`previous.sample` = "click")
app$snapshot()
app$setInputs(`previous.sample` = "click")
app$snapshot()

p <- app$.__enclos_env__$private$shinyProcess
p$interrupt()
p$wait()
