app <- ShinyDriver$new("../../", loadTimeout = 100000, seed = 1234)
app$snapshotInit("marker_select")

Sys.sleep(0.5)
app$setInputs(Marker_1 = "CD99")
app$setInputs(tabbox1 = "tab2")
#app$snapshot()
app$setInputs(resetMarkers = "click")
#app$snapshot()
app$setInputs(Marker_2 = "PIN")
app$snapshot()
app$setInputs(tabbox1 = "tab2")
#app$snapshot()
app$setInputs(resetMarkers = "click")
#app$snapshot()
app$setInputs(Marker_2 = "CDH")
app$snapshot()
app$setInputs(tabbox1 = "tab2")
#app$snapshot()
app$setInputs(resetMarkers = "click")
#app$snapshot()
app$setInputs(exprs_marker_1 = "H3")
#app$snapshot()
app$setInputs(exprs_marker_2 = "CD8a")
#app$snapshot()
app$setInputs(resetMarkers = "click")
#app$snapshot()

p <- app$.__enclos_env__$private$shinyProcess
p$interrupt()
p$wait()
